name: Deploy Node.js App to Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '6.6.0'  # ya jo version Beanstalk me ho

    - name: Zip source code
      run: zip -r source.zip . -x ".git/*" ".github/*" "node_modules/*"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 cp source.zip s3://my-elastic-bucket1/source.zip

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name todo \
          --version-label v-${{ github.run_number }} \
          --source-bundle S3Bucket=my-elastic-bucket1,S3Key=source.zip

        aws elasticbeanstalk update-environment \
          --environment-name Todo-env \
          --version-label v-${{ github.run_number }}
